package token

var LexerTypes = map[string]string{
	"WS":         "[ \t]+",
	"COMMENT":    "//.*",
	"IDENTIFIER": "[a-zA-Z_][a-zA-Z0-9_]*",
	"INTEGER":    "-?[0-9]+",
	"FLOAT":      "-?[0-9]+\\.[0-9]+",
	"STRING":     "\"[^\"]*\"",
	"BOOLEAN":    "true|false",
	"OPERATOR":   "[+\\-*/%<>=&|^!~\\?]",
	"CONDITION":  "[!=<>]=?",
	"LPAREN":     "(",
	"RPAREN":     ")",
	"LBRACE":     "{",
	"RBRACE":     "}",
	"LBRACKET":   "[",
	"RBRACKET":   "]",
	"COMMA":      ",",
	"SEMICOLON":  ";",
	"COLON":      ":",
	"DOT":        "\\.",
	"AND":        "&&",
	"OR":         "||",
	"NOT":        "!",
	"BITAND":     "&",
	"BITOR":      "|",
	"BITXOR":     "^",
	"BITNOT":     "~",
	"BITLSHIFT":  "<<",
	"BITRSHIFT":  ">>",
	"NL":         "\n",
	"EOF":        "",
}
